- hosts: all
  gather_facts: False
  become: yes
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: install wget
    apt:
      name: wget
      state: present

  - name: install openjdk
    apt:
      name: openjdk-8-jdk
      state: present

  - name: download jenkins.repo
    shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

  - name: import jenkins key
    apt_key:
      url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
      state: present

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: install jenkins
    apt:
      name: jenkins
      state: present

  - name: start jenkins
    systemd:
      name: jenkins
      state: started

  - name: enable jenkins
    systemd:
      name: jenkins
      enabled: true

  - name: sleep for 30 seconds and continue with play
    wait_for: timeout=30
    delegate_to: localhost

  - name: init password jenkin
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result

  - name: print init password jenkins
    debug:
      var: result.stdout

  - name: Get my public IP from ipify.org
    ipify_facts:

  - name: URL to the web aplication
    debug: msg='{{ ipify_public_ip }}'

#Confirm the connection of Jenkins on the Web (specify the password of result.stdout)
